name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout-code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Docker-login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo "Iniciando login"
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        echo "Finalizando login"

    - name: Docker-build-image
      run: |
        echo "Iniciando contruccion de imagen"
        docker build -t jjce/docker-graphql:0.0.2 .
        echo "Finalizando contruccion de imagen"

    - name: Docker-push-image
      run: |
        echo "Iniciando subida repositorio docker hub"
        docker push jjce/docker-graphql:0.0.2 .
        echo "Finalizando  subida repositorio docker hub"
    # - name: Build the Docker image
    #   run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
